import type { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    name: 'Modern Downtown Apartment',
    location: 'New York, USA',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'modern apartment',
    pricePerFraction: 150,
    totalFractions: 1000,
    availableFractions: 650,
    description: 'A stunning modern apartment in the heart of downtown, offering breathtaking city views and luxury amenities.',
    propertyType: 'Apartment',
    dateAdded: new Date('2023-10-15T10:00:00Z').toISOString(),
  },
  {
    id: '2',
    name: 'Spacious Suburban House',
    location: 'London, UK',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'suburban house',
    pricePerFraction: 250,
    totalFractions: 2000,
    availableFractions: 1200,
    description: 'A beautiful and spacious house in a quiet suburban neighborhood, perfect for families.',
    propertyType: 'House',
    dateAdded: new Date('2023-11-01T14:30:00Z').toISOString(),
  },
  {
    id: '3',
    name: 'Beachfront Villa',
    location: 'Malibu, USA',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'beachfront villa',
    pricePerFraction: 500,
    totalFractions: 5000,
    availableFractions: 2500,
    description: 'An exquisite beachfront villa with direct access to the ocean and panoramic views.',
    propertyType: 'House',
    dateAdded: new Date('2023-09-20T09:00:00Z').toISOString(),
  },
  {
    id: '4',
    name: 'Commercial Office Space',
    location: 'Tokyo, Japan',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'office space',
    pricePerFraction: 300,
    totalFractions: 3000,
    availableFractions: 1500,
    description: 'Prime commercial office space in a bustling business district, ideal for startups and established companies.',
    propertyType: 'Commercial',
    dateAdded: new Date('2023-12-01T11:00:00Z').toISOString(),
  },
  {
    id: '5',
    name: 'Cozy Mountain Cabin',
    location: 'Aspen, USA',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'mountain cabin',
    pricePerFraction: 180,
    totalFractions: 800,
    availableFractions: 300,
    description: 'A cozy cabin nestled in the mountains, offering a perfect retreat with stunning natural surroundings.',
    propertyType: 'House',
    dateAdded: new Date('2024-01-10T16:00:00Z').toISOString(),
  },
  {
    id: '6',
    name: 'Urban Loft with Rooftop Terrace',
    location: 'Berlin, Germany',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'urban loft',
    pricePerFraction: 220,
    totalFractions: 1200,
    availableFractions: 750,
    description: 'Stylish urban loft featuring an open-plan living space and a private rooftop terrace with city views.',
    propertyType: 'Apartment',
    dateAdded: new Date('2024-02-01T12:00:00Z').toISOString(),
  },
];

export const PROPERTY_TYPES: Property['propertyType'][] = ['Apartment', 'House', 'Commercial', 'Land'];